server.port: 8803
spring:
  datasource:
    name:
    host:
    #type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.203:3306/business-work-order
    username: root
    password: root
